name = "zexo"
workers_dev = true
compatibility_date = "2026-05-24"
account_id = "18a4be16ffbe9059c7820d123caff0b7"
main = "./index.js"
[[kv_namespaces]]
binding = "KVNAME"
id = "83df7b3228a94bd4bb7fbd3f510f1940"
preview_id = "83df7b3228a94bd4bb7fbd3f510f1940"